security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                #default_target_path: default_security_target
            logout:
                handlers: [app.logout_handler]
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

        - { path: ^/books$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/books/download/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/books/view/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/books/, role: ROLE_ADMIN }

        - { path: ^/authors$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/authors/, role: ROLE_ADMIN }

        - { path: ^/genres$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/genres/, role: ROLE_ADMIN }

        - { path: ^/series$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/series/, role: ROLE_ADMIN }

        - { path: ^/archive/, role: IS_AUTHENTICATED_FULLY }

        - { path: ^/export, role: ROLE_ADMIN }