# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      gedmo.listener.softdeleteable:
          class: Gedmo\SoftDeleteable\SoftDeleteableListener

      app.authors:
          class: AppBundle\Service\Authors
          arguments: ["@doctrine"]

      app.books:
          class: AppBundle\Service\Books
          arguments: ["@doctrine", "%library%"]

      app.genres:
           class: AppBundle\Service\Genres
           arguments: ["@doctrine"]

      app.series:
          class: AppBundle\Service\Series
          arguments: ["@doctrine"]

      app.ratings:
            class: AppBundle\Service\Ratings
            arguments: ["@doctrine"]

      app.comments:
            class: AppBundle\Service\Comments
            arguments: ["@doctrine"]

      app.sessions:
            class: AppBundle\Service\Sessions
            arguments: ["@request_stack", "@doctrine"]

      app.archives:
            class: AppBundle\Service\Archives
            arguments: ["@=service('request_stack').getCurrentRequest().getSession()","@doctrine", "%session_archive_var%", "%library%", "@=service('security.token_storage').getToken().getUser()"]

      app.kernel_event_subscriber:
            class: AppBundle\EventListener\KernelEventSubscriber
            arguments: ["@kernel", "@security.token_storage", "%library%"]
            tags:
                - { name: kernel.event_subscriber }

      app.comment_voter:
            class:  AppBundle\Security\CommentVoter
            tags:
                - { name: security.voter }
            public: false