imports:
    - { resource: voters.yml }

services:
      gedmo.listener.softdeleteable:
          class: Gedmo\SoftDeleteable\SoftDeleteableListener

      app.base_service:
          class: AppBundle\Service\BaseService
          abstract: true
          calls:
            - [setDoctrine, ['@doctrine']]

      app.export:
          public: true
          parent: app.base_service
          class: AppBundle\Service\Export\Exporter
          arguments: ["%export%"]

      app.authors:
          public: true
          parent: app.base_service
          class: AppBundle\Service\Authors
          arguments: ["@app.export", "@translator"]

      app.books:
          public: true
          parent: app.base_service
          class: AppBundle\Service\Books
          arguments: ["@request_stack", "@validator", "%library%"]

      app.genres:
           public: true
           parent: app.base_service
           class: AppBundle\Service\Genres
           arguments: ["@app.export", "@translator"]

      app.series:
          public: true
          parent: app.base_service
          class: AppBundle\Service\Series
          arguments: ["@app.export", "@translator"]

      app.ratings:
          public: true
          parent: app.base_service
          class: AppBundle\Service\Ratings

      app.comments:
          public: true
          parent: app.base_service
          class: AppBundle\Service\Comments

      app.sessions:
          public: true
          parent: app.base_service
          class: AppBundle\Service\Sessions
          arguments: ["@request_stack"]

      app.archives:
          public: true
          parent: app.base_service
          class: AppBundle\Service\Archives
          arguments: ["@security.token_storage"]
          calls:
            - [setRedis, ['@snc_redis.default']]

      app.online:
          public: true
          class: AppBundle\Service\Online\Online
          calls:
            - [setRedis, ['@snc_redis.default']]

      app.cache_service:
          public: true
          class: AppBundle\Service\Cache\CacheService
          arguments: ["@knp_paginator", "%kernel.environment%"]
          calls:
            - [setRedis, ['@snc_redis.cache']]

#     app.random_thumbnail:
#         class: AppBundle\Twig\AppExtension
#         arguments: ["@router"]
#         tags:
#                - { name: twig.extension }

      app.kernel_exception_listener:
          class: AppBundle\EventListener\PDOExceptionListener
          tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onPDOException }

      app.authentication_failure_event_subscriber:
          class: AppBundle\EventListener\LoginSubscriber
          arguments: ["@security.token_storage", "@request_stack", "@monolog.logger.security"]
          calls:
            - [setRedis, ['@snc_redis.default']]
          tags:
            - { name: kernel.event_subscriber }

      app.request_listener:
          class: AppBundle\EventListener\RequestListener
          arguments: ["@security.token_storage", "@app.online"]
          tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

      app.logout_handler:
          class: AppBundle\Security\Handler\LogoutHandler
          arguments: ["@app.online"]

      app.mailer:
          public: true
          class: AppBundle\Service\Mail\Mailer
          arguments: ["@swiftmailer.mailer.rabbitmq", "@templating", "@router.default"]

      app.consumer.mail:
          class: AppBundle\Consumer\MailConsumer
          arguments: ["@app.mailer"]

      app.book_subscriber:
          class: AppBundle\EventListener\BookSubscriber
          arguments: ["@monolog.logger.library", "@old_sound_rabbit_mq.send_email_producer", "%kernel.environment%", "%admin_email%"]
          tags:
            - { name: kernel.event_subscriber }

      app.book_entity_subscriber:
          class: AppBundle\EventListener\BookEntitySubscriber
          arguments: ["@app.cache_service"]
          tags:
            - { name: doctrine.event_subscriber }

      app.book_service_facade:
          public: true
          class: AppBundle\Service\Facade\BookServiceFacade
          arguments: ["@app.archives", "@app.books", "@app.cache_service", "@app.sessions"]
