imports:
    - { resource: voters.yml }

parameters:
#    parameter_name: value

services:
      gedmo.listener.softdeleteable:
          class: Gedmo\SoftDeleteable\SoftDeleteableListener

      app.export:
          class: AppBundle\Service\Export\Export
          arguments: ["%export%"]
          calls:
            - [setDoctrine, ['@doctrine']]

      app.authors:
          class: AppBundle\Service\Authors
          arguments: ["@app.export", "@translator"]
          calls:
            - [setDoctrine, ['@doctrine']]

      app.books:
          class: AppBundle\Service\Books
          arguments: ["@request_stack", "@validator", "%library%"]
          calls:
            - [setDoctrine, ['@doctrine']]

      app.genres:
           class: AppBundle\Service\Genres
           arguments: ["@app.export", "@translator"]
           calls:
            - [setDoctrine, ['@doctrine']]

      app.series:
          class: AppBundle\Service\Series
          arguments: ["@app.export", "@translator"]
          calls:
            - [setDoctrine, ['@doctrine']]

      app.ratings:
          class: AppBundle\Service\Ratings
          calls:
            - [setDoctrine, ['@doctrine']]

      app.comments:
          class: AppBundle\Service\Comments
          calls:
            - [setDoctrine, ['@doctrine']]

      app.sessions:
          class: AppBundle\Service\Sessions
          arguments: ["@request_stack"]
          calls:
            - [setDoctrine, ['@doctrine']]

      app.archives:
          class: AppBundle\Service\Archives
          arguments: ["@security.token_storage"]
          calls:
            - [setRedis, ['@snc_redis.default']]
            - [setDoctrine, ['@doctrine']]

#     app.random_thumbnail:
#         class: AppBundle\Twig\AppExtension
#         arguments: ["@router"]
#         tags:
#                - { name: twig.extension }

      app.kernel_exception_listener:
          class: AppBundle\EventListener\PDOExceptionListener
          tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onPDOException }

      app.authentication_failure_event_subscriber:
          class: AppBundle\EventListener\LoginSubscriber
          arguments: ["@snc_redis.default", "@security.token_storage", "@request_stack", "@monolog.logger.security"]
          tags:
            - { name: kernel.event_subscriber }

      app.request_litener:
          class: AppBundle\EventListener\RequestListener
          arguments: ["@snc_redis.default", "@security.token_storage"]
          tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

      app.logout_handler:
          class: AppBundle\Security\Handler\LogoutHandler
          arguments: ["@snc_redis.default"]
